parameters:
  lift_distance: 0.3
  drop_distance: 0.3
  conveyor_speed: 0.2
  conveyor_belt_length: 2.8

pose_timers:
  approach_time: 11.0
  pick_time: 13.5
  retreat_time: 15.0
  place_time: 20.0

bin_origins:
  gasket_part:
    pose:
      xyz: [-0.3, 1.2, 0.9]
      rpy: [0, 0, 0]
  piston_rod_part:
    pose:
      xyz: [-0.3, 0.4, 0.9]
      rpy: [0, 0, 0]
  gear_part:
    pose:
      xyz: [-0.3, 0.4, 0.9]
      rpy: [0, 0, 0]
  disk_part:
    pose:
      xyz: [-0.3, -1.2, 0.9]
      rpy: [0, 0, 0]
  pulley_part:
    pose:
      xyz: [-0.3, -2.0, 0.9]
      rpy: [0, 0, 0]


robot_origin:
  pose:
    xyz: [1.0, 0.0, 0.0]
    rpy: [0, 0, 0]   
